default_locale: en-EN
fields:
  - name: test
    nullRate: 0.1
    locale: ru-RU
    generators: [ net.datafaker.providers.base.Name#lastName ]
  - name: test
    nullable: true
    generators: [ Name#firstName ]
  - name: test"2
    type: array
    nullable: false
    locale: ja-JP
    minLength: 2
    maxLength: 5
    generators: [ Name#firstName, Name#lastName ]
  - name: test"6
    type: struct
    nullable: false
    fields:
      - name: test"4
        nullable: false
        generators: [ Name#firstName, Name#lastName ]
      - name: test"3
        nullable: false
        generators: [ Name#firstName, Name#lastName ]

